### ISSUE TITLE
Conversion error on monokai include

### ISSUE THREAD

**Issue by 2bithacker** [brijeshb42/bitwiser#3]
Ran into the following issue trying to use the bitwiser theme today:
```
Configuration file: /Users/chip/Personal/2bithacker.github.io/_config.yml
            Source: /Users/chip/Personal/2bithacker.github.io
       Destination: /Users/chip/Personal/2bithacker.github.io/_site
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error converting 'css/style.scss'.
  Conversion error: File to import not found or unreadable: monokai. Load path: /Users/chip/Personal/2bithacker.github.io/_sass
jekyll 2.4.0 | Error:  File to import not found or unreadable: monokai.
Load path: /Users/chip/Personal/2bithacker.github.io/_sass
```

**Comment by brijeshb42** [comment]
The _sass directory should have the following files.
![screen shot 2015-02-16 at 10 57 36 pm](https://cloud.githubusercontent.com/assets/717550/6216351/60be51e6-b62f-11e4-9ae8-e867f954d960.png)

I have recently changed the css file structure. Earlier, `monokai.css` was in css directory in the theme folder.
Now it has been moved to `_sass` and renamed to `monokai.scss`.
You should do a `git pull` and retry to see if error persists or not.
