### ISSUE TITLE
How would I remove the blog from the homepage to another page? 

### ISSUE THREAD

**Issue by tryagains** [brijeshb42/bitwiser#4]
Hey I notice you made the blog the homepage. I was wondering how would I switch that up? I tried removing the index.html content into a blog.html file but then the blog no longer works. I am guessing the blog is attached to the name "index.html" but where can I find this?

**Comment by brijeshb42** [comment]
@tryagains Hey, I have created a [subdirectory](https://github.com/brijeshb42/bitwiser/tree/subdirectory) branch just for this issue. It has basic instructions on how to setup the blog as per your requirements in the `index.md` file. Do check it out and give your feedback.

**Comment by tryagains** [comment]
thanks @brijeshb42 works great
