### ISSUE TITLE
Drop Down menu

### ISSUE THREAD

**Issue by piotr-yuxuan** [brijeshb42/bitwiser#5]
Hi guy, thanks a lot fot this beautiful site theme I'm planning to use \o/

Actually this is not really an issue but more a request to extend that theme: could you add drop down menu? :-) I mean, something like this: http://codepen.io/philhoyt/pen/ujHzd
As you say pull requests are welcome, I can try to do it by myself if you tell me which file I should put new code in: I don't feel very comfortable yet with scss.

**Comment by brijeshb42** [comment]
How many levels of submenu do you want?

**Comment by piotr-yuxuan** [comment]
Thanks for your reply!
Ha ha, basically the general solution would be « n > 1, with automatic positioning », but actually no, just 1 sublevel will be perfect. If you just give me hint, I can try to do it by myself -- scss is easier to get started with then expected :-)

**Comment by brijeshb42** [comment]
@piotr-yuxuan I am working on it. But if you want, you can update scss styles in `css/styles.scss` and add sub menu in `_includes/header.html` .

**Comment by piotr-yuxuan** [comment]
Ok, I've got a proposal here: https://piotr-yuxuan.github.io/

It's only a proposal because -- you'll very quickly understand why but I'm not that good in CSS and I believe you could correct that bug easily. I've don't either know how to give an automatic width to sub-items. Last remark, it disappears when mobile mode, but I think it's not that bad -- it would take some time to make a proper mobile-adapted sub-menu.

You can notice I put links and your name in he About section, so we know who thie theme comes from ~

**Comment by brijeshb42** [comment]
I am adding support for single level submenu in my next commit.

**Comment by piotr-yuxuan** [comment]
great, thanks!

**Comment by piotr-yuxuan** [comment]
Heya :-) just a short message to know when you'll commit it. As you can see in my proposal, there is something wrong I haven't managed to fix.

**Comment by piotr-yuxuan** [comment]
unresolved, moving to another theme.
