### ISSUE TITLE
Suggestion to keep users of this theme up to date

### ISSUE THREAD

**Issue by piotr-yuxuan** [brijeshb42/bitwiser#6]
I'm using your theme and I'm thinking it'd be nice just to get last improvements you could give it just with `git pull`. However, git pull would also retrieve your personal content you also put in this repository.

Thus, may I suggest you to clean this repo (or make a new `bitwiser-theme` repo) with only theme files ? then a user would be able to pull changes from your 'official' repo more easily.Thanks ~

**Comment by brijeshb42** [comment]
This is only theme repository. There is no personal content. That is in [other repository(//github.com/brijeshb42/brijeshb42.github.io) .

**Comment by piotr-yuxuan** [comment]
OK, sorry I felt it was not. Thanks :-)
