### ISSUE TITLE
CSS not displaying on posts

### ISSUE THREAD

**Issue by skydusk** [brijeshb42/bitwiser#7]
Hello, I can't seem to get CSS displaying correctly for posts (the rest of the site works fine).

http://skydusk.github.io/

As you can see the first test post doesn't display properly: http://skydusk.github.io/2015/08/27/Test.html

Do you know what I'm doing wrong here? Also many thanks for this design, its one of my jekyll favourites

**Comment by brijeshb42** [comment]
In https://github.com/skydusk/skydusk.github.io/blob/master/_layouts/default.html#L15 , add a `/` before `css`. It should be 
`<link rel="stylesheet" href="/css/style.css">`
Notice the '/' before `css/style.css`

**Comment by skydusk** [comment]
yes someone managed to tell me the exact same thing a few minutes ago, everything is displaying correctly now.

once again thank you for this theme, its really great.
