### ISSUE TITLE
Is this theme support categories ?

### ISSUE THREAD

**Issue by archersmind** [brijeshb42/bitwiser#9]
Hi,

This is a great theme. It is already support categories or suppose to ?

Thanks

**UPDATE:**

`categories` here I mean, posts from different category are listed in the main page like:

![screenshot from 2015-09-22 12 05 37](https://cloud.githubusercontent.com/assets/1461331/10010786/de34d692-6122-11e5-86c8-6a449259b74a.png)

**Comment by brijeshb42** [comment]
You can specify **category** in the YAML front matter of the post and the post will belong to that category and will have a related URL like `/categoryname/2015-09-24-post-title.html`. But currently the theme does not have any functionality of generating the list of categories and their number of posts as above.
